Ext.define('Project2.project2.shared.projecttwo.model.appinsight.health.BugModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "bugId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bugName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "component",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "priority",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});