Ext.define('Project2.project2.shared.projecttwo.model.appinsight.health.EmployeeModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "empId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "empName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "empSal",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});